/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mkyong.rmiserver;


/**
 *
 * @author naki_
 */
public class GUIServer extends javax.swing.JFrame {

    /**
     * Creates new form GUIServer
     */
    public GUIServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        _tblClientTask = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        _lblRemainWork = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _lblWorkStatus = new javax.swing.JLabel();
        _btnStartTask = new javax.swing.JButton();
        _btnOpenFileLocation = new javax.swing.JButton();
        _btnEndTask = new javax.swing.JButton();
        _btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _tblClientTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Client ID", "Task ID", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(_tblClientTask);
        if (_tblClientTask.getColumnModel().getColumnCount() > 0) {
            _tblClientTask.getColumnModel().getColumn(0).setResizable(false);
            _tblClientTask.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Total Remaining Work");

        _lblRemainWork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        String remainWork = "";
        //if(JobSchedule.unSortTask.size()!=0){
            //    remainWork = String.valueOf(JobSchedule.unSortTask.size());
            //}
        _lblRemainWork.setText(remainWork);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Work Status");

        _lblWorkStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _lblWorkStatus.setText("Idle");

        _btnStartTask.setText("Start");
        _btnStartTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnStartTaskActionPerformed(evt);
            }
        });

        _btnOpenFileLocation.setText("Open File Location");

        _btnEndTask.setText("End Task");

        _btnExit.setText("Exit");
        _btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_btnStartTask)
                        .addGap(41, 41, 41)
                        .addComponent(_btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_btnEndTask))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_lblWorkStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(117, 117, 117)
                                .addComponent(_lblRemainWork)
                                .addGap(11, 11, 11)))
                        .addGap(18, 18, 18)
                        .addComponent(_btnOpenFileLocation)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_lblRemainWork))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_lblWorkStatus)
                    .addComponent(_btnOpenFileLocation))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnEndTask)
                    .addComponent(_btnStartTask)
                    .addComponent(_btnExit))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnStartTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnStartTaskActionPerformed
        new Thread()
        {
            public void run() {
                Server.testMergeSort();
                Server.init();
            }
        }.start();
        // TODO add your handling code here:
    }//GEN-LAST:event__btnStartTaskActionPerformed

    private void _btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        JobSchedule jobS = new JobSchedule();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                String a;
//                a = String.valueOf(JobSchedule.unSortTask2.size());
                
                new GUIServer().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnEndTask;
    private javax.swing.JButton _btnExit;
    private javax.swing.JButton _btnOpenFileLocation;
    private javax.swing.JButton _btnStartTask;
    private javax.swing.JLabel _lblRemainWork;
    private javax.swing.JLabel _lblWorkStatus;
    private javax.swing.JTable _tblClientTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
