/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mkyong.rmiclient;

import com.mkyong.rmiinterface.Const;

/**
 *
 * @author Micky
 */
public class MainUI extends javax.swing.JFrame {
    private static JobClient client;
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setBounds(500, 250, 500, 200);
        this._text_server_ip.setText(Const._IP_Server);
        this._text_conn_stat.setText(Const._TXT_NotConnect);
        this._text_status_client.setText(Const._TXT_WaitForJob);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _btn_start = new javax.swing.JButton();
        _btn_stop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        _text_server_ip = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        _text_conn_stat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _text_conn_jobID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _text_data1_size = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _text_size_data2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _text_status_client = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _btn_start.setText("Start");
        _btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_startActionPerformed(evt);
            }
        });

        _btn_stop.setText("Stop");
        _btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_stopActionPerformed(evt);
            }
        });

        jLabel1.setText("Server ip :");

        _text_server_ip.setText("none");

        jLabel2.setText("Connect status :");

        _text_conn_stat.setText("none");

        jLabel3.setText("Current Job ID :");

        _text_conn_jobID.setText("none");

        jLabel4.setText("Size Data_1 :");

        _text_data1_size.setText("none");

        jLabel5.setText("Size Data_2 :");

        _text_size_data2.setText("none");

        jLabel6.setText("Status Client :");

        _text_status_client.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_text_data1_size))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(_text_server_ip))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_text_conn_jobID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_text_size_data2)))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_btn_start)
                                .addGap(18, 18, 18)
                                .addComponent(_btn_stop))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_text_status_client))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_text_conn_stat)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_text_server_ip)
                    .addComponent(jLabel2)
                    .addComponent(_text_conn_stat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(_text_conn_jobID)
                    .addComponent(jLabel6)
                    .addComponent(_text_status_client))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_text_data1_size))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(_text_size_data2)
                    .addComponent(_btn_start)
                    .addComponent(_btn_stop))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_startActionPerformed
        client.startClient();
    }//GEN-LAST:event__btn_startActionPerformed

    private void _btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_stopActionPerformed
        client.stopClient();
    }//GEN-LAST:event__btn_stopActionPerformed
    
    public void setTextStatClient(String s){
        this._text_status_client.setText(s);
    }
    
    public void setTextCurrentJob(String s){
        this._text_conn_jobID.setText(s);
    }
    
    public void setTextData1Size(String s){
        this._text_data1_size.setText(s);
    }
    
    public void setTextData2Size(String s){
        this._text_size_data2.setText(s);
    }
    
    public void setTextConnStatus(String s){
        this._text_conn_stat.setText(s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainUI ui = new MainUI();
                ui.setVisible(true);
                client = new JobClient(ui);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_start;
    private javax.swing.JButton _btn_stop;
    private javax.swing.JLabel _text_conn_jobID;
    private javax.swing.JLabel _text_conn_stat;
    private javax.swing.JLabel _text_data1_size;
    private javax.swing.JLabel _text_server_ip;
    private javax.swing.JLabel _text_size_data2;
    private javax.swing.JLabel _text_status_client;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
